mysql:
  # dns : root:root@tcp(127.0.0.1:3306)/newbee?charset=utf8mb4&parseTime=True&loc=Local
  dns : root:root@tcp(121.37.200.179:3306)/newbee?charset=utf8mb4&parseTime=True&loc=Local
# redis:
#   addr : "127.0.0.1:6379"
#   password : ""
#   DB : 0
#   PoolSize : 30
#   MinIdleConns : 30

